import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./ui/header/Header";
import "@/app/ui/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body className={inter.className}>
        <Header />
        <div className="main">{children}</div>
      </body>
    </html>
  );
}
